-d C:\Users\marco\Documents\fpga_project\sdr\impl\gwsynthesis\sdr.vg
-p GW1NR-9C-QFN88P-6
-pn GW1NR-LV9QN88PC6/I5
-cst C:\Users\marco\Documents\fpga_project\sdr\src\sdr.cst
-cfg C:\Users\marco\Documents\fpga_project\sdr\impl\pnr\device.cfg
-sdc C:\Users\marco\Documents\fpga_project\sdr\src\sdr.sdc
-bit
-tr
-ph
-timing
-cst_error
-route_maxfan 23
